language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - CODECOV_TOKEN="c3c4f94a-4c8d-4f07-be90-cdb21259f67f"
  matrix:
    - ANDROID_API_LEVEL=android-23 ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=android-28 ANDROID_ABI=armeabi-v7a

  android:
    components:
      - tools
      - platform-tools
      - tools
      - extra-android-m2repository
    licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
        
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/app/.gradle/caches/
  - $HOME/app/.gradle/wrapper/
  - $HOME/app/.android/build-cache

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - pip install --user codecov

before_script:
  - cd app
  - chmod +x gradlew
  - ./gradlew build customJacocoTestReport assembleAndroidTest
  
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug createDebugUnitTestCoverageReport
  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: 
  - "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"